Updated test script for status
hyperledgerkochi/KOBman pull request #118
Opened 2020-07-07 07:25 UTC by ananashraf

- State change is being considered.

Instructions :
- Go to your local repository of KOBman and run the following command from tests/commands
    ./test-kob-status dummyenv 0.0.3 ( other versions are 0.0.2 ,0.0.5)

Output : 
----------

![Screenshot from 2020-07-07 12-50-27](https://user-images.githubusercontent.com/30839287/86735710-9badd980-c050-11ea-8a4f-48e878562578.png)

Failing Condition :
- Run the following command : ./test-kob-status dummyenv 0.0.1
![image](https://user-images.githubusercontent.com/30839287/86736246-ff380700-c050-11ea-8701-cd6180abaaa3.png)

2020-07-07 07:26 UTC, ananashraf commented
Please ignore the kobman-help.sh file.

2020-07-07 08:10 UTC, asa1997 commented
LGTM

2020-07-07 12:09 UTC, panickervinod commented on tests/commands/test-kob-status.sh
> +    export INTERACTIVE_MODE="false"
Please rename INTERACTIVE_MODE to KOBMAN_INTERACTIVE_USER_MODE, all KOBman export variables will have KOBMAN_ prefix.

2020-07-14 08:18 UTC, asa1997 commented
@ananashraf Please close this pull request and raise a new one with the requested changes

2020-07-14 08:19 UTC, asa1997 requested changes
@ananashraf  Please close this pull request and raise a new one with the said changes.

2020-07-14 19:08 UTC, closed without merging